# Site settings
title: DTZ Vorbereitung Notizbuch by vshanbha
short_name: DTZN
logo: "/assets/logos/logo.svg"
description: >- # this means to ignore newlines until "baseurl:"
  Ein Online-Notizbuch, das bei der Vorbereitung auf den Deutschtest für Zuwanderer (DTZ) hilft. Enthält Flashcards, um den deutschen Wortschatz zu erweitern.
baseurl: "/DTZNotizbuch" # the subpath of your site, e.g. /blog
url: "https://vshanbha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vshanbha
repository: "vshanbha/DTZNotizbuch"
css_inline: false

# Build settings
# remote_theme: "mmistakes/jekyll-theme-basically-basic"
theme: "alembic-jekyll-theme"
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# Gem Settings
paginate: 10 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page

# Jekyll Settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - CNAME
  - PULL_REQUEST_TEMPLATE.md
  - screenshot.png
  - alembic-jekyll-theme.gemspec

# General Configuration
defaults:
  # _posts
  - 
    scope:
      path: ""
      type: posts
    values:
      read_time: true
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "team"
    values:
      layout: team_member

navigation_header:
- title: Hauptseite
  url: /
- title: Flashcards
  url: /flashcards/
- title: Über uns
  url: /about/
- title: Team
  url: /team/
- title: Readme
  url: /readme/

navigation_footer:
- title: Home
  url: /
- title: About
  ur: /about/

favicons:
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  192: '/assets/logos/logo@192px.png'  
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
# Theme specific Configuration
      
collections:
  team:
    output: true
    permalink: /team/:path/
  flashcards:
    output: false
  pages:
    output: true
    permalink: /:path/

data_dir: _data 
